app.id: mywp
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${username}
    password: ${password}
  redis:
    host: 39.99.187.162
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

logging:
  config: classpath:logback-spring.xml
  level:
    dao: debug
    org:
      mybatis: debug



